{{config(materialized ='incremental', unique_key='HOST_ID')}}

SELECT 
HOST_ID,
REPLACE(HOST_NAME,' ', '_') as HOST_NAME,
HOST_SINCE,
IS_SUPERHOST,
RESPONSE_RATE,
CASE 
WHEN RESPONSE_RATE> 95 THEN 'EXCELLENT'
WHEN RESPONSE_RATE > 80 then 'GOOD'
WHEN RESPONSE_RATE > 60 THEN 'AVERAGE'
ELSE 'POOR'
END
as RESPONSE_RATE_CATEGORY,
CREATED_AT

FROM 
{{ref ('bronze_hosts')}}